# Generated by Django 2.0.4 on 2018-04-25 07:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object', '0003_auto_20180425_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=200)),
                ('SLUG', models.SlugField(max_length=500)),
                ('BODY', models.TextField()),
                ('CREATE_DT', models.DateTimeField(default=datetime.datetime(2018, 4, 25, 7, 51, 13, 87953, tzinfo=utc))),
                ('LAST_DT', models.DateTimeField(auto_now=True)),
                ('AUTHOR', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DailyReplay', to=settings.AUTH_USER_MODEL)),
                ('OBJECT', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='object.Objects')),
            ],
            options={
                'ordering': ('TITLE',),
            },
        ),
        migrations.AlterIndexTogether(
            name='dailyreplay',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='dailyreplay',
            name='AUTHOR',
        ),
        migrations.RemoveField(
            model_name='dailyreplay',
            name='OBJECT',
        ),
        migrations.DeleteModel(
            name='DailyReplay',
        ),
        migrations.AlterIndexTogether(
            name='report',
            index_together={('id', 'SLUG')},
        ),
    ]
