# Generated by Django 2.0.4 on 2018-04-27 06:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object', '0004_auto_20180425_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='USER_LIKE',
            field=models.ManyToManyField(blank=True, related_name='report_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='AUTHOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='CREATE_DT',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 6, 21, 7, 913315, tzinfo=utc)),
        ),
    ]
