# Generated by Django 2.0.2 on 2018-03-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialinfo',
            old_name='TOT_LIAT',
            new_name='TOT_LIAB',
        ),
    ]
