# Generated by Django 2.0.2 on 2018-03-22 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20180322_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('COUNTRY_CODE', models.CharField(help_text='代码', max_length=20, primary_key=True, serialize=False, verbose_name='代码')),
                ('COUNTRY_NAME', models.CharField(help_text='国家名称', max_length=20, verbose_name='国家名称')),
            ],
        ),
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'ordering': ['COUNTRY', 'ASSETS', 'TRADE_CODE']},
        ),
        migrations.AlterField(
            model_name='currency',
            name='CURRENCY_NAME',
            field=models.CharField(help_text='货币名称', max_length=20, verbose_name='货币名称'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='COUNTRY',
            field=models.ForeignKey(help_text='标的所属国家', null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.country', verbose_name='标的所属国家'),
        ),
    ]
