# Generated by Django 2.0.2 on 2018-03-22 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_country_country_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='COUNTRY',
            field=models.ForeignKey(help_text='国家', null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.country', verbose_name='国家'),
        ),
    ]
