# Generated by Django 2.0.2 on 2018-03-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20180322_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinfo',
            name='ACCT_PAYABLE',
            field=models.DecimalField(decimal_places=4, help_text='应付账款', max_digits=20, null=True, verbose_name='应付账款'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='ACCT_RCV',
            field=models.DecimalField(decimal_places=4, help_text='应收账款', max_digits=20, null=True, verbose_name='应收账款'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='ADV_FROM_CUST',
            field=models.DecimalField(decimal_places=4, help_text='预收账款', max_digits=20, null=True, verbose_name='预收账款'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='CASH_CASH_EQU_END_PERIOD',
            field=models.DecimalField(decimal_places=4, help_text='期末现金及现金等价物余额', max_digits=20, null=True, verbose_name='期末现金及现金等价物余额'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='CASH_PAY_ACQ_CONST_FIOLTA',
            field=models.DecimalField(decimal_places=4, help_text='构建固定资产、无形资产和其他长期资产支付的现金', max_digits=20, null=True, verbose_name='构建固定资产、无形资产和其他长期资产支付的现金'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='CASH_PAY_BEH_EMPL',
            field=models.DecimalField(decimal_places=4, help_text='支付给职工以及为职工支付的现金', max_digits=20, null=True, verbose_name='支付给职工以及为职工支付的现金'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='CASH_RECP_SG_AND_RS',
            field=models.DecimalField(decimal_places=4, help_text='销售商品、提供劳务收到的现金', max_digits=20, null=True, verbose_name='销售商品、提供劳务收到的现金'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='CONST_IN_PROG',
            field=models.DecimalField(decimal_places=4, help_text='在建工程', max_digits=20, null=True, verbose_name='在建工程'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='DEPR_FA_COGA_DPBA',
            field=models.DecimalField(decimal_places=4, help_text='固定资产折旧、油气资产这好、生产性生物资产折旧', max_digits=20, null=True, verbose_name='固定资产折旧、油气资产这好、生产性生物资产折旧'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='EMPLOYEE',
            field=models.IntegerField(help_text='员工数', null=True, verbose_name='员工数'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='EMPLOYEE_BA',
            field=models.IntegerField(help_text='本科', null=True, verbose_name='本科'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='EMPLOYEE_MS',
            field=models.IntegerField(help_text='硕士', null=True, verbose_name='硕士'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='EQY_BELONGTO_PARCOMSH',
            field=models.DecimalField(decimal_places=4, help_text='归属母公司股东的权益', max_digits=20, null=True, verbose_name='归属母公司股东的权益'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='EXTRAORDINARY',
            field=models.DecimalField(decimal_places=4, help_text='非经常性损益', max_digits=20, null=True, verbose_name='非经常性损益'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='FIN_EXP_IS',
            field=models.DecimalField(decimal_places=4, help_text='财务费用', max_digits=20, null=True, verbose_name='财务费用'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='FIX_ASSETS',
            field=models.DecimalField(decimal_places=4, help_text='固定资产', max_digits=20, null=True, verbose_name='固定资产'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='GERL_ADMIN_EXP',
            field=models.DecimalField(decimal_places=4, help_text='管理费用', max_digits=20, null=True, verbose_name='管理费用'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='GOODWILL',
            field=models.DecimalField(decimal_places=4, help_text='商誉', max_digits=20, null=True, verbose_name='商誉'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='HOLDER_PCTBYFUND',
            field=models.DecimalField(decimal_places=4, help_text='基金持股比例', max_digits=20, null=True, verbose_name='基金持股比例'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='HOLDER_PCTBYQFII',
            field=models.DecimalField(decimal_places=4, help_text='QFII持股比例', max_digits=20, null=True, verbose_name='QFII持股比例'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='HOLDER_PCTBYSSFUND',
            field=models.DecimalField(decimal_places=4, help_text='社保持股比例', max_digits=20, null=True, verbose_name='社保持股比例'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='INTANG_ASSETS',
            field=models.DecimalField(decimal_places=4, help_text='无形资产', max_digits=20, null=True, verbose_name='无形资产'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='INTERESTDEBT',
            field=models.DecimalField(decimal_places=4, help_text='带息债务', max_digits=20, null=True, verbose_name='带息债务'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='INVENTORIES',
            field=models.DecimalField(decimal_places=4, help_text='存货', max_digits=20, null=True, verbose_name='存货'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='MONETARY_CAP',
            field=models.DecimalField(decimal_places=4, help_text='货币资产', max_digits=20, null=True, verbose_name='货币资产'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='NET_CASH_FLOWS_FNC_ACT',
            field=models.DecimalField(decimal_places=4, help_text='筹资活动产生的现金流量净额', max_digits=20, null=True, verbose_name='筹资活动产生的现金流量净额'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='NET_CASH_FLOWS_INV_ACT',
            field=models.DecimalField(decimal_places=4, help_text='投资活动产生的现金流量净额', max_digits=20, null=True, verbose_name='投资活动产生的现金流量净额'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='NET_CASH_FLOWS_OPER_ACT',
            field=models.DecimalField(decimal_places=4, help_text='经营活动产生的现金流量净额', max_digits=20, null=True, verbose_name='经营活动产生的现金流量净额'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='NET_PROFIT_IS',
            field=models.DecimalField(decimal_places=4, help_text='净利润', max_digits=20, null=True, verbose_name='净利润'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='NOTES_PAYABLE',
            field=models.DecimalField(decimal_places=4, help_text='应付票据', max_digits=20, null=True, verbose_name='应付票据'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='NOTES_RCV',
            field=models.DecimalField(decimal_places=4, help_text='应收票据', max_digits=20, null=True, verbose_name='应收票据'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='NP_BELONGTO_PARCOMSH',
            field=models.DecimalField(decimal_places=4, help_text='归属于母公司普通股东综合收益总额', max_digits=20, null=True, verbose_name='归属于母公司普通股东综合收益总额'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='OPER_COST',
            field=models.DecimalField(decimal_places=4, help_text='营业成本', max_digits=20, null=True, verbose_name='营业成本'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='OPER_REV',
            field=models.DecimalField(decimal_places=4, help_text='营业收入', max_digits=20, null=True, verbose_name='营业收入'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='OPPROFIT',
            field=models.DecimalField(decimal_places=4, help_text='营业利润', max_digits=20, null=True, verbose_name='营业利润'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='OTH_CUR_ASSETS',
            field=models.DecimalField(decimal_places=4, help_text='其他流动资产', max_digits=20, null=True, verbose_name='其他流动资产'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='OTH_RCV',
            field=models.DecimalField(decimal_places=4, help_text='其它应收款', max_digits=20, null=True, verbose_name='其它应收款'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='PREPAY',
            field=models.DecimalField(decimal_places=4, help_text='预付账款', max_digits=20, null=True, verbose_name='预付账款'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='RESEARCHANDDEVELOPMENTEXPENSES',
            field=models.DecimalField(decimal_places=4, help_text='研发费用', max_digits=20, null=True, verbose_name='研发费用'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='SEC_NAME',
            field=models.CharField(help_text='名称', max_length=100, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='SEGMENT_INDUSTRY_PROFIT',
            field=models.DecimalField(decimal_places=4, help_text='主营构成（按行业）-项目利润', max_digits=20, null=True, verbose_name='主营构成（按行业）-项目利润'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='SEGMENT_INDUSTRY_SALES',
            field=models.DecimalField(decimal_places=4, help_text='主营构成（按行业）-项目收入', max_digits=20, null=True, verbose_name='主营构成（按行业）-项目收入'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='SELLING_DIST_EXP',
            field=models.DecimalField(decimal_places=4, help_text='销售费用', max_digits=20, null=True, verbose_name='销售费用'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='STMNOTE_PROFITAPR_3',
            field=models.DecimalField(decimal_places=4, help_text='可分配利润', max_digits=20, null=True, verbose_name='可分配利润'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='STMNOTE_PROFITAPR_4',
            field=models.DecimalField(decimal_places=4, help_text='支付普通股股利', max_digits=20, null=True, verbose_name='支付普通股股利'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='STMNOTE_SEG_1501',
            field=models.DecimalField(decimal_places=4, help_text='海外业务收入', max_digits=20, null=True, verbose_name='海外业务收入'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='TOT_ASSETS',
            field=models.DecimalField(decimal_places=4, help_text='资产总计', max_digits=20, null=True, verbose_name='资产总计'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='TOT_CUR_ASSETS',
            field=models.DecimalField(decimal_places=4, help_text='流动资产合计', max_digits=20, null=True, verbose_name='流动资产合计'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='TOT_CUR_LIAB',
            field=models.DecimalField(decimal_places=4, help_text='流动负债合计', max_digits=20, null=True, verbose_name='流动负债合计'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='TOT_LIAB',
            field=models.DecimalField(decimal_places=4, help_text='负债合计', max_digits=20, null=True, verbose_name='负债合计'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='TRADABLE_FIN_ASSETS',
            field=models.DecimalField(decimal_places=4, help_text='交易性金融资产', max_digits=20, null=True, verbose_name='交易性金融资产'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='UNDISTRIBUTED_PROFIT',
            field=models.DecimalField(decimal_places=4, help_text='未分配利润', max_digits=20, null=True, verbose_name='未分配利润'),
        ),
    ]
