# Generated by Django 2.0.2 on 2018-03-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20180322_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetsinfo',
            options={'verbose_name': '资产表'},
        ),
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'ordering': ['COUNTRY', 'ASSETS', 'TRADE_CODE'], 'verbose_name': '标的表'},
        ),
        migrations.AlterModelOptions(
            name='basictree',
            options={'ordering': ['TRADE_CODE', 'CHILD_CODE', 'DT'], 'verbose_name': '关系表'},
        ),
        migrations.AlterModelOptions(
            name='classinfo',
            options={'verbose_name': '类别信息表'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '国家表'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': '货币表'},
        ),
        migrations.AlterModelOptions(
            name='financialinfo',
            options={'verbose_name': '财务基础数据表'},
        ),
        migrations.AlterModelOptions(
            name='indexinfo',
            options={'verbose_name': '指数信息表'},
        ),
        migrations.AlterModelOptions(
            name='marketinfo',
            options={'verbose_name': '市场基础数据表'},
        ),
        migrations.AlterModelOptions(
            name='stockinfo',
            options={'verbose_name': '股票信息表'},
        ),
    ]
