# Generated by Django 2.0.2 on 2018-03-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20180322_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='obos',
            fields=[
                ('ID', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('DT', models.DateField(verbose_name='日期')),
                ('VALUE', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='超买超卖数值')),
                ('SIGNAL', models.IntegerField(verbose_name='阈值信号')),
                ('TRADE_CODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.basicinfo', verbose_name='板块代码')),
            ],
            options={
                'verbose_name': '超买超卖表',
            },
        ),
        migrations.RemoveField(
            model_name='financialinfo',
            name='SEC_NAME',
        ),
        migrations.RemoveField(
            model_name='marketinfo',
            name='SEC_NAME',
        ),
        migrations.AddIndex(
            model_name='obos',
            index=models.Index(fields=['TRADE_CODE', 'DT'], name='market_obos_TRADE_C_27608d_idx'),
        ),
        migrations.AddIndex(
            model_name='obos',
            index=models.Index(fields=['TRADE_CODE'], name='obos_tc'),
        ),
    ]
