# Generated by Django 2.0.2 on 2018-04-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20180322_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='obos',
            name='AA',
            field=models.IntegerField(default=0, verbose_name='test'),
            preserve_default=False,
        ),
    ]
